variables:
  LATEX_IMAGE: texlive/texlive:latest

stages:
  - build
  - release

build_assets:
  stage: build
  image:
    name: $LATEX_IMAGE
  script:
    - make gitlab
  artifacts:
    paths:
      - build/unpacked/maine-thesis.cls
      - maine-thesis.tds.zip
      - "maine-thesis-*.zip"
      - template.zip
    expire_in: 1 week
  # This section is updated from 'except:' to 'rules:'
  rules:
    - if: $CI_COMMIT_TAG

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_assets
      artifacts: true
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release created for tag $CI_COMMIT_TAG' # You can add a description file here too
    assets:
      links:
        - name: 'maine-thesis.cls'
          # This path points directly to the artifact from the 'build_assets' job
          filepath: /build/unpacked/maine-thesis.cls
        - name: 'maine-thesis.tds.zip'
          filepath: /maine-thesis.tds.zip
        - name: 'maine-thesis-template.zip'
          filepath: /template.zip
        #
        #- name: 'maine-thesis-${CI_COMMIT_TAG#v}.zip'
        #  filepath: '/maine-thesis-${CI_COMMIT_TAG#v}.zip'
  rules:
    - if: $CI_COMMIT_TAG